/*
Copyright (c) 2013 Max Lungarella

This file is part of Aips2SQLite.

Aips2SQLite is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 12:25:30 PM CEST 
//

package com.maxl.java.aips2sqlite;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Limitation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LimitationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LimitationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LimitationNiveau" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LimitationValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DescriptionDe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DescriptionFr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DescriptionIt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ValidFromDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ValidThruDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "limitation"
})
@XmlRootElement(name = "Limitations")
public class Limitations {

    @XmlElement(name = "Limitation")
    protected List<Limitations.Limitation> limitation;

    /**
     * Gets the value of the limitation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the limitation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLimitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Limitations.Limitation }
     * 
     * 
     */
    public List<Limitations.Limitation> getLimitation() {
        if (limitation == null) {
            limitation = new ArrayList<Limitations.Limitation>();
        }
        return this.limitation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LimitationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LimitationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LimitationNiveau" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LimitationValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DescriptionDe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DescriptionFr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DescriptionIt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ValidFromDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ValidThruDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "limitationCode",
        "limitationType",
        "limitationNiveau",
        "limitationValue",
        "descriptionDe",
        "descriptionFr",
        "descriptionIt",
        "validFromDate",
        "validThruDate"
    })
    public static class Limitation {

        @XmlElement(name = "LimitationCode")
        protected String limitationCode;
        @XmlElement(name = "LimitationType")
        protected String limitationType;
        @XmlElement(name = "LimitationNiveau")
        protected String limitationNiveau;
        @XmlElement(name = "LimitationValue")
        protected String limitationValue;
        @XmlElement(name = "DescriptionDe")
        protected String descriptionDe;
        @XmlElement(name = "DescriptionFr")
        protected String descriptionFr;
        @XmlElement(name = "DescriptionIt")
        protected String descriptionIt;
        @XmlElement(name = "ValidFromDate")
        protected String validFromDate;
        @XmlElement(name = "ValidThruDate")
        protected String validThruDate;

        /**
         * Gets the value of the limitationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLimitationCode() {
            return limitationCode;
        }

        /**
         * Sets the value of the limitationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLimitationCode(String value) {
            this.limitationCode = value;
        }

        /**
         * Gets the value of the limitationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLimitationType() {
            return limitationType;
        }

        /**
         * Sets the value of the limitationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLimitationType(String value) {
            this.limitationType = value;
        }

        /**
         * Gets the value of the limitationNiveau property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLimitationNiveau() {
            return limitationNiveau;
        }

        /**
         * Sets the value of the limitationNiveau property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLimitationNiveau(String value) {
            this.limitationNiveau = value;
        }

        /**
         * Gets the value of the limitationValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLimitationValue() {
            return limitationValue;
        }

        /**
         * Sets the value of the limitationValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLimitationValue(String value) {
            this.limitationValue = value;
        }

        /**
         * Gets the value of the descriptionDe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescriptionDe() {
            return descriptionDe;
        }

        /**
         * Sets the value of the descriptionDe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescriptionDe(String value) {
            this.descriptionDe = value;
        }

        /**
         * Gets the value of the descriptionFr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescriptionFr() {
            return descriptionFr;
        }

        /**
         * Sets the value of the descriptionFr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescriptionFr(String value) {
            this.descriptionFr = value;
        }

        /**
         * Gets the value of the descriptionIt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescriptionIt() {
            return descriptionIt;
        }

        /**
         * Sets the value of the descriptionIt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescriptionIt(String value) {
            this.descriptionIt = value;
        }

        /**
         * Gets the value of the validFromDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidFromDate() {
            return validFromDate;
        }

        /**
         * Sets the value of the validFromDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidFromDate(String value) {
            this.validFromDate = value;
        }

        /**
         * Gets the value of the validThruDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidThruDate() {
            return validThruDate;
        }

        /**
         * Sets the value of the validThruDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidThruDate(String value) {
            this.validThruDate = value;
        }

    }

}

