/*
Copyright (c) 2013 Max Lungarella

This file is part of Aips2SQLite.

Aips2SQLite is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 10:30:08 PM CEST 
//

package com.maxl.java.aips2sqlite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ITEM" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GTIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PHAR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="STDATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LANG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DSCR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ADDSCR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ATC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="COMP" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="GLN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="DT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RESULT" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OK_ERROR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="NBR_RECORD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CREATION_DATETIME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "result"
})
@XmlRootElement(name = "PHARMA")
public class Pharma {

    @XmlElement(name = "ITEM")
    protected List<Pharma.ITEM> item;
    @XmlElement(name = "RESULT")
    protected List<Pharma.RESULT> result;
    @XmlAttribute(name = "CREATION_DATETIME")
    protected String creationdatetime;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getITEM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PHARMA.ITEM }
     * 
     * 
     */
    public List<Pharma.ITEM> getItem() {
        if (item == null) {
            item = new ArrayList<Pharma.ITEM>();
        }
        return this.item;
    }

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRESULT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PHARMA.RESULT }
     * 
     * 
     */
    public List<Pharma.RESULT> getResult() {
        if (result == null) {
            result = new ArrayList<Pharma.RESULT>();
        }
        return this.result;
    }

    /**
     * Gets the value of the creationdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDateTime() {
        return creationdatetime;
    }

    /**
     * Sets the value of the creationdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDateTime(String value) {
        this.creationdatetime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GTIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PHAR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="STDATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LANG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DSCR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ADDSCR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ATC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="COMP" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="GLN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="DT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gtin",
        "phar",
        "status",
        "stdate",
        "lang",
        "dscr",
        "addscr",
        "atc",
        "comp"
    })
    public static class ITEM {

        @XmlElement(name = "GTIN")
        protected String gtin;
        @XmlElement(name = "PHAR")
        protected String phar;
        @XmlElement(name = "STATUS")
        protected String status;
        @XmlElement(name = "STDATE")
        protected String stdate;
        @XmlElement(name = "LANG")
        protected String lang;
        @XmlElement(name = "DSCR")
        protected String dscr;
        @XmlElement(name = "ADDSCR")
        protected String addscr;
        @XmlElement(name = "ATC")
        protected String atc;
        @XmlElement(name = "COMP")
        protected List<Pharma.ITEM.COMP> comp;
        @XmlAttribute(name = "DT")
        protected String dt;

        /**
         * Gets the value of the gtin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGtin() {
            return gtin;
        }

        /**
         * Sets the value of the gtin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGtin(String value) {
            this.gtin = value;
        }

        /**
         * Gets the value of the phar property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhar() {
            return phar;
        }

        /**
         * Sets the value of the phar property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhar(String value) {
            this.phar = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the stdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStdate() {
            return stdate;
        }

        /**
         * Sets the value of the stdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStdate(String value) {
            this.stdate = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

        /**
         * Gets the value of the dscr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDscr() {
            return dscr;
        }

        /**
         * Sets the value of the dscr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDscr(String value) {
            this.dscr = value;
        }

        /**
         * Gets the value of the addscr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddscr() {
            return addscr;
        }

        /**
         * Sets the value of the addscr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddscr(String value) {
            this.addscr = value;
        }

        /**
         * Gets the value of the atc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAtc() {
            return atc;
        }

        /**
         * Sets the value of the atc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAtc(String value) {
            this.atc = value;
        }

        /**
         * Gets the value of the comp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCOMP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PHARMA.ITEM.COMP }
         * 
         * 
         */
        public List<Pharma.ITEM.COMP> getComp() {
            if (comp == null) {
                comp = new ArrayList<Pharma.ITEM.COMP>();
            }
            return this.comp;
        }

        /**
         * Gets the value of the dt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDt() {
            return dt;
        }

        /**
         * Sets the value of the dt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDt(String value) {
            this.dt = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="GLN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "gln"
        })
        public static class COMP {

            @XmlElement(name = "NAME")
            protected String name;
            @XmlElement(name = "GLN")
            protected String gln;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the gln property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGln() {
                return gln;
            }

            /**
             * Sets the value of the gln property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGln(String value) {
                this.gln = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OK_ERROR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="NBR_RECORD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "okerror",
        "nbrrecord"
    })
    public static class RESULT {

        @XmlElement(name = "OK_ERROR")
        protected String okerror;
        @XmlElement(name = "NBR_RECORD")
        protected String nbrrecord;

        /**
         * Gets the value of the okerror property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOkError() {
            return okerror;
        }

        /**
         * Sets the value of the okerror property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOkError(String value) {
            this.okerror = value;
        }

        /**
         * Gets the value of the nbrrecord property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNbrRecord() {
            return nbrrecord;
        }

        /**
         * Sets the value of the nbrrecord property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNbrRecord(String value) {
            this.nbrrecord = value;
        }
    }
}