/*
Copyright (c) 2013 Max Lungarella

This file is part of Aips2SQLite.

Aips2SQLite is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 12:25:30 PM CEST 
//

package com.maxl.java.aips2sqlite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IntegrationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValidFromDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValidThruDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusTypeCodeSl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusTypeDescriptionSl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FlagApd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "integrationDate",
    "validFromDate",
    "validThruDate",
    "statusTypeCodeSl",
    "statusTypeDescriptionSl",
    "flagApd"
})
@XmlRootElement(name = "Status")
public class Status {

    @XmlElement(name = "IntegrationDate")
    protected String integrationDate;
    @XmlElement(name = "ValidFromDate")
    protected String validFromDate;
    @XmlElement(name = "ValidThruDate")
    protected String validThruDate;
    @XmlElement(name = "StatusTypeCodeSl")
    protected String statusTypeCodeSl;
    @XmlElement(name = "StatusTypeDescriptionSl")
    protected String statusTypeDescriptionSl;
    @XmlElement(name = "FlagApd")
    protected String flagApd;

    /**
     * Gets the value of the integrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrationDate() {
        return integrationDate;
    }

    /**
     * Sets the value of the integrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrationDate(String value) {
        this.integrationDate = value;
    }

    /**
     * Gets the value of the validFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidFromDate() {
        return validFromDate;
    }

    /**
     * Sets the value of the validFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidFromDate(String value) {
        this.validFromDate = value;
    }

    /**
     * Gets the value of the validThruDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidThruDate() {
        return validThruDate;
    }

    /**
     * Sets the value of the validThruDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidThruDate(String value) {
        this.validThruDate = value;
    }

    /**
     * Gets the value of the statusTypeCodeSl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusTypeCodeSl() {
        return statusTypeCodeSl;
    }

    /**
     * Sets the value of the statusTypeCodeSl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusTypeCodeSl(String value) {
        this.statusTypeCodeSl = value;
    }

    /**
     * Gets the value of the statusTypeDescriptionSl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusTypeDescriptionSl() {
        return statusTypeDescriptionSl;
    }

    /**
     * Sets the value of the statusTypeDescriptionSl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusTypeDescriptionSl(String value) {
        this.statusTypeDescriptionSl = value;
    }

    /**
     * Gets the value of the flagApd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagApd() {
        return flagApd;
    }

    /**
     * Sets the value of the flagApd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagApd(String value) {
        this.flagApd = value;
    }

}

