//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.06.04 at 08:01:21 PM JST
//


package com.maxl.java.aips2sqlite.refdata;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Article" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MedicinalProduct">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Gmn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="LegalStatusOfSupply" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="RegulatedAuthorisationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ProductClassification">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ProductClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Atc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PackagedProduct">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RegulatedAuthorisationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DataCarrierIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Holder" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Name" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="MarketingStatus">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DateStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="DateStop" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DocumentReference" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Hpc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="ProductPrice" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RetailPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="totalArticles" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="generatedOn" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "article"
})
@XmlRootElement(name = "Articles")
public class Articles {

    @XmlElement(name = "Article", required = true)
    protected List<Articles.Article> article;
    @XmlAttribute(name = "totalArticles", required = true)
    protected int totalArticles;
    @XmlAttribute(name = "generatedOn", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar generatedOn;

    /**
     * Gets the value of the article property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the article property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticle().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Articles.Article }
     *
     *
     */
    public List<Articles.Article> getArticle() {
        if (article == null) {
            article = new ArrayList<Articles.Article>();
        }
        return this.article;
    }

    /**
     * Gets the value of the totalArticles property.
     *
     */
    public int getTotalArticles() {
        return totalArticles;
    }

    /**
     * Sets the value of the totalArticles property.
     *
     */
    public void setTotalArticles(int value) {
        this.totalArticles = value;
    }

    /**
     * Gets the value of the generatedOn property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getGeneratedOn() {
        return generatedOn;
    }

    /**
     * Sets the value of the generatedOn property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setGeneratedOn(XMLGregorianCalendar value) {
        this.generatedOn = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MedicinalProduct">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Gmn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="LegalStatusOfSupply" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="RegulatedAuthorisationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ProductClassification">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ProductClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Atc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PackagedProduct">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RegulatedAuthorisationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DataCarrierIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Holder" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Name" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="MarketingStatus">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DateStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                             &lt;element name="DateStop" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="DocumentReference" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Hpc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="ProductPrice" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RetailPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "medicinalProduct",
        "packagedProduct",
        "documentReference",
        "hpc",
        "productPrice"
    })
    public static class Article {

        @XmlElement(name = "MedicinalProduct", required = true)
        protected Articles.Article.MedicinalProduct medicinalProduct;
        @XmlElement(name = "PackagedProduct", required = true)
        protected Articles.Article.PackagedProduct packagedProduct;
        @XmlElement(name = "DocumentReference")
        protected List<Articles.Article.DocumentReference> documentReference;
        @XmlElement(name = "Hpc")
        protected Boolean hpc;
        @XmlElement(name = "ProductPrice")
        protected Articles.Article.ProductPrice productPrice;

        /**
         * Gets the value of the medicinalProduct property.
         *
         * @return
         *     possible object is
         *     {@link Articles.Article.MedicinalProduct }
         *
         */
        public Articles.Article.MedicinalProduct getMedicinalProduct() {
            return medicinalProduct;
        }

        /**
         * Sets the value of the medicinalProduct property.
         *
         * @param value
         *     allowed object is
         *     {@link Articles.Article.MedicinalProduct }
         *
         */
        public void setMedicinalProduct(Articles.Article.MedicinalProduct value) {
            this.medicinalProduct = value;
        }

        /**
         * Gets the value of the packagedProduct property.
         *
         * @return
         *     possible object is
         *     {@link Articles.Article.PackagedProduct }
         *
         */
        public Articles.Article.PackagedProduct getPackagedProduct() {
            return packagedProduct;
        }

        /**
         * Sets the value of the packagedProduct property.
         *
         * @param value
         *     allowed object is
         *     {@link Articles.Article.PackagedProduct }
         *
         */
        public void setPackagedProduct(Articles.Article.PackagedProduct value) {
            this.packagedProduct = value;
        }

        /**
         * Gets the value of the documentReference property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documentReference property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocumentReference().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Articles.Article.DocumentReference }
         *
         *
         */
        public List<Articles.Article.DocumentReference> getDocumentReference() {
            if (documentReference == null) {
                documentReference = new ArrayList<Articles.Article.DocumentReference>();
            }
            return this.documentReference;
        }

        /**
         * Gets the value of the hpc property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        public Boolean isHpc() {
            return hpc;
        }

        /**
         * Sets the value of the hpc property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setHpc(Boolean value) {
            this.hpc = value;
        }

        /**
         * Gets the value of the productPrice property.
         *
         * @return
         *     possible object is
         *     {@link Articles.Article.ProductPrice }
         *
         */
        public Articles.Article.ProductPrice getProductPrice() {
            return productPrice;
        }

        /**
         * Sets the value of the productPrice property.
         *
         * @param value
         *     allowed object is
         *     {@link Articles.Article.ProductPrice }
         *
         */
        public void setProductPrice(Articles.Article.ProductPrice value) {
            this.productPrice = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "language",
            "url"
        })
        public static class DocumentReference {

            @XmlElement(name = "Language", required = true)
            protected String language;
            @XmlElement(name = "Url", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String url;

            /**
             * Gets the value of the language property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLanguage(String value) {
                this.language = value;
            }

            /**
             * Gets the value of the url property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Gmn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="LegalStatusOfSupply" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="RegulatedAuthorisationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ProductClassification">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ProductClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Atc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "identifier",
            "domain",
            "gmn",
            "legalStatusOfSupply",
            "regulatedAuthorisationIdentifier",
            "productClassification"
        })
        public static class MedicinalProduct {

            @XmlElement(name = "Identifier", required = true)
            protected String identifier;
            @XmlElement(name = "Domain")
            protected String domain;
            @XmlElement(name = "Gmn")
            protected String gmn;
            @XmlElement(name = "LegalStatusOfSupply")
            protected String legalStatusOfSupply;
            @XmlElement(name = "RegulatedAuthorisationIdentifier")
            protected String regulatedAuthorisationIdentifier;
            @XmlElement(name = "ProductClassification", required = true)
            protected Articles.Article.MedicinalProduct.ProductClassification productClassification;

            /**
             * Gets the value of the identifier property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getIdentifier() {
                return identifier;
            }

            /**
             * Sets the value of the identifier property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setIdentifier(String value) {
                this.identifier = value;
            }

            /**
             * Gets the value of the domain property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDomain() {
                return domain;
            }

            /**
             * Sets the value of the domain property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDomain(String value) {
                this.domain = value;
            }

            /**
             * Gets the value of the gmn property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getGmn() {
                return gmn;
            }

            /**
             * Sets the value of the gmn property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setGmn(String value) {
                this.gmn = value;
            }

            /**
             * Gets the value of the legalStatusOfSupply property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLegalStatusOfSupply() {
                return legalStatusOfSupply;
            }

            /**
             * Sets the value of the legalStatusOfSupply property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLegalStatusOfSupply(String value) {
                this.legalStatusOfSupply = value;
            }

            /**
             * Gets the value of the regulatedAuthorisationIdentifier property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRegulatedAuthorisationIdentifier() {
                return regulatedAuthorisationIdentifier;
            }

            /**
             * Sets the value of the regulatedAuthorisationIdentifier property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRegulatedAuthorisationIdentifier(String value) {
                this.regulatedAuthorisationIdentifier = value;
            }

            /**
             * Gets the value of the productClassification property.
             *
             * @return
             *     possible object is
             *     {@link Articles.Article.MedicinalProduct.ProductClassification }
             *
             */
            public Articles.Article.MedicinalProduct.ProductClassification getProductClassification() {
                return productClassification;
            }

            /**
             * Sets the value of the productClassification property.
             *
             * @param value
             *     allowed object is
             *     {@link Articles.Article.MedicinalProduct.ProductClassification }
             *
             */
            public void setProductClassification(Articles.Article.MedicinalProduct.ProductClassification value) {
                this.productClassification = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ProductClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Atc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "productClass",
                "atc"
            })
            public static class ProductClassification {

                @XmlElement(name = "ProductClass", required = true)
                protected String productClass;
                @XmlElement(name = "Atc")
                protected String atc;

                /**
                 * Gets the value of the productClass property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getProductClass() {
                    return productClass;
                }

                /**
                 * Sets the value of the productClass property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setProductClass(String value) {
                    this.productClass = value;
                }

                /**
                 * Gets the value of the atc property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getAtc() {
                    return atc;
                }

                /**
                 * Sets the value of the atc property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setAtc(String value) {
                    this.atc = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RegulatedAuthorisationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DataCarrierIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Holder" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Name" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="MarketingStatus">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DateStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *                   &lt;element name="DateStop" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "identifier",
            "regulatedAuthorisationIdentifier",
            "dataCarrierIdentifier",
            "holder",
            "name",
            "marketingStatus"
        })
        public static class PackagedProduct {

            @XmlElement(name = "Identifier", required = true)
            protected String identifier;
            @XmlElement(name = "RegulatedAuthorisationIdentifier")
            protected String regulatedAuthorisationIdentifier;
            @XmlElement(name = "DataCarrierIdentifier", required = true)
            protected String dataCarrierIdentifier;
            @XmlElement(name = "Holder")
            protected Articles.Article.PackagedProduct.Holder holder;
            @XmlElement(name = "Name", required = true)
            protected List<Articles.Article.PackagedProduct.Name> name;
            @XmlElement(name = "MarketingStatus", required = true)
            protected Articles.Article.PackagedProduct.MarketingStatus marketingStatus;

            /**
             * Gets the value of the identifier property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getIdentifier() {
                return identifier;
            }

            /**
             * Sets the value of the identifier property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setIdentifier(String value) {
                this.identifier = value;
            }

            /**
             * Gets the value of the regulatedAuthorisationIdentifier property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRegulatedAuthorisationIdentifier() {
                return regulatedAuthorisationIdentifier;
            }

            /**
             * Sets the value of the regulatedAuthorisationIdentifier property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRegulatedAuthorisationIdentifier(String value) {
                this.regulatedAuthorisationIdentifier = value;
            }

            /**
             * Gets the value of the dataCarrierIdentifier property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDataCarrierIdentifier() {
                return dataCarrierIdentifier;
            }

            /**
             * Sets the value of the dataCarrierIdentifier property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDataCarrierIdentifier(String value) {
                this.dataCarrierIdentifier = value;
            }

            /**
             * Gets the value of the holder property.
             *
             * @return
             *     possible object is
             *     {@link Articles.Article.PackagedProduct.Holder }
             *
             */
            public Articles.Article.PackagedProduct.Holder getHolder() {
                return holder;
            }

            /**
             * Sets the value of the holder property.
             *
             * @param value
             *     allowed object is
             *     {@link Articles.Article.PackagedProduct.Holder }
             *
             */
            public void setHolder(Articles.Article.PackagedProduct.Holder value) {
                this.holder = value;
            }

            /**
             * Gets the value of the name property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the name property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getName().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Articles.Article.PackagedProduct.Name }
             *
             *
             */
            public List<Articles.Article.PackagedProduct.Name> getName() {
                if (name == null) {
                    name = new ArrayList<Articles.Article.PackagedProduct.Name>();
                }
                return this.name;
            }

            /**
             * Gets the value of the marketingStatus property.
             *
             * @return
             *     possible object is
             *     {@link Articles.Article.PackagedProduct.MarketingStatus }
             *
             */
            public Articles.Article.PackagedProduct.MarketingStatus getMarketingStatus() {
                return marketingStatus;
            }

            /**
             * Sets the value of the marketingStatus property.
             *
             * @param value
             *     allowed object is
             *     {@link Articles.Article.PackagedProduct.MarketingStatus }
             *
             */
            public void setMarketingStatus(Articles.Article.PackagedProduct.MarketingStatus value) {
                this.marketingStatus = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "identifier",
                "name"
            })
            public static class Holder {

                @XmlElement(name = "Identifier", required = true)
                protected String identifier;
                @XmlElement(name = "Name", required = true)
                protected String name;

                /**
                 * Gets the value of the identifier property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getIdentifier() {
                    return identifier;
                }

                /**
                 * Sets the value of the identifier property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setIdentifier(String value) {
                    this.identifier = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DateStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
             *         &lt;element name="DateStop" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dateStart",
                "dateStop"
            })
            public static class MarketingStatus {

                @XmlElement(name = "DateStart", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar dateStart;
                @XmlElement(name = "DateStop")
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar dateStop;

                /**
                 * Gets the value of the dateStart property.
                 *
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public XMLGregorianCalendar getDateStart() {
                    return dateStart;
                }

                /**
                 * Sets the value of the dateStart property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public void setDateStart(XMLGregorianCalendar value) {
                    this.dateStart = value;
                }

                /**
                 * Gets the value of the dateStop property.
                 *
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public XMLGregorianCalendar getDateStop() {
                    return dateStop;
                }

                /**
                 * Sets the value of the dateStop property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public void setDateStop(XMLGregorianCalendar value) {
                    this.dateStop = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "language",
                "fullName"
            })
            public static class Name {

                @XmlElement(name = "Language", required = true)
                protected String language;
                @XmlElement(name = "FullName", required = true)
                protected String fullName;

                /**
                 * Gets the value of the language property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getLanguage() {
                    return language;
                }

                /**
                 * Sets the value of the language property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setLanguage(String value) {
                    this.language = value;
                }

                /**
                 * Gets the value of the fullName property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getFullName() {
                    return fullName;
                }

                /**
                 * Sets the value of the fullName property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setFullName(String value) {
                    this.fullName = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RetailPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "retailPrice"
        })
        public static class ProductPrice {

            @XmlElement(name = "RetailPrice", required = true)
            protected BigDecimal retailPrice;

            /**
             * Gets the value of the retailPrice property.
             *
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *
             */
            public BigDecimal getRetailPrice() {
                return retailPrice;
            }

            /**
             * Sets the value of the retailPrice property.
             *
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *
             */
            public void setRetailPrice(BigDecimal value) {
                this.retailPrice = value;
            }

        }

    }

}
