//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.09.19 at 06:19:43 PM JST
//


package com.maxl.java.aips2sqlite.refdata;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MedicinalDocumentsBundle" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Type" type="{https://simisinfo.refdata.ch/MedicinalDocuments/1.0/}TypeType"/>
 *                   &lt;element name="RegulatedAuthorization">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Holder">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Language" type="{https://simisinfo.refdata.ch/MedicinalDocuments/1.0/}LanguageType"/>
 *                   &lt;element name="MainLanguageDocumentChanged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="AttachedDocument" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Language" type="{https://simisinfo.refdata.ch/MedicinalDocuments/1.0/}LanguageType"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Period">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Start" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DocumentReference" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="generatedOn" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "medicinalDocumentsBundle"
})
@XmlRootElement(name = "MedicinalDocumentsBundles")
public class MedicinalDocumentsBundles {

    @XmlElement(name = "MedicinalDocumentsBundle", required = true)
    protected List<MedicinalDocumentsBundles.MedicinalDocumentsBundle> medicinalDocumentsBundle;
    @XmlAttribute(name = "generatedOn", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar generatedOn;

    /**
     * Gets the value of the medicinalDocumentsBundle property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicinalDocumentsBundle property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicinalDocumentsBundle().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle }
     *
     *
     */
    public List<MedicinalDocumentsBundles.MedicinalDocumentsBundle> getMedicinalDocumentsBundle() {
        if (medicinalDocumentsBundle == null) {
            medicinalDocumentsBundle = new ArrayList<MedicinalDocumentsBundles.MedicinalDocumentsBundle>();
        }
        return this.medicinalDocumentsBundle;
    }

    /**
     * Gets the value of the generatedOn property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getGeneratedOn() {
        return generatedOn;
    }

    /**
     * Sets the value of the generatedOn property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setGeneratedOn(XMLGregorianCalendar value) {
        this.generatedOn = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Type" type="{https://simisinfo.refdata.ch/MedicinalDocuments/1.0/}TypeType"/>
     *         &lt;element name="RegulatedAuthorization">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Holder">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Language" type="{https://simisinfo.refdata.ch/MedicinalDocuments/1.0/}LanguageType"/>
     *         &lt;element name="MainLanguageDocumentChanged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="AttachedDocument" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Language" type="{https://simisinfo.refdata.ch/MedicinalDocuments/1.0/}LanguageType"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Period">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Start" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DocumentReference" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "domain",
        "type",
        "regulatedAuthorization",
        "holder",
        "language",
        "mainLanguageDocumentChanged",
        "attachedDocument"
    })
    public static class MedicinalDocumentsBundle {

        @XmlElement(name = "Date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "Domain", required = true)
        protected String domain;
        @XmlElement(name = "Type", required = true)
        @XmlSchemaType(name = "string")
        protected TypeType type;
        @XmlElement(name = "RegulatedAuthorization", required = true)
        protected MedicinalDocumentsBundles.MedicinalDocumentsBundle.RegulatedAuthorization regulatedAuthorization;
        @XmlElement(name = "Holder", required = true)
        protected MedicinalDocumentsBundles.MedicinalDocumentsBundle.Holder holder;
        @XmlElement(name = "Language", required = true)
        @XmlSchemaType(name = "string")
        protected LanguageType language;
        @XmlElement(name = "MainLanguageDocumentChanged")
        protected boolean mainLanguageDocumentChanged;
        @XmlElement(name = "AttachedDocument", required = true)
        protected List<MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument> attachedDocument;

        /**
         * Gets the value of the date property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the domain property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDomain() {
            return domain;
        }

        /**
         * Sets the value of the domain property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDomain(String value) {
            this.domain = value;
        }

        /**
         * Gets the value of the type property.
         *
         * @return
         *     possible object is
         *     {@link TypeType }
         *
         */
        public TypeType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value
         *     allowed object is
         *     {@link TypeType }
         *
         */
        public void setType(TypeType value) {
            this.type = value;
        }

        /**
         * Gets the value of the regulatedAuthorization property.
         *
         * @return
         *     possible object is
         *     {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.RegulatedAuthorization }
         *
         */
        public MedicinalDocumentsBundles.MedicinalDocumentsBundle.RegulatedAuthorization getRegulatedAuthorization() {
            return regulatedAuthorization;
        }

        /**
         * Sets the value of the regulatedAuthorization property.
         *
         * @param value
         *     allowed object is
         *     {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.RegulatedAuthorization }
         *
         */
        public void setRegulatedAuthorization(MedicinalDocumentsBundles.MedicinalDocumentsBundle.RegulatedAuthorization value) {
            this.regulatedAuthorization = value;
        }

        /**
         * Gets the value of the holder property.
         *
         * @return
         *     possible object is
         *     {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.Holder }
         *
         */
        public MedicinalDocumentsBundles.MedicinalDocumentsBundle.Holder getHolder() {
            return holder;
        }

        /**
         * Sets the value of the holder property.
         *
         * @param value
         *     allowed object is
         *     {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.Holder }
         *
         */
        public void setHolder(MedicinalDocumentsBundles.MedicinalDocumentsBundle.Holder value) {
            this.holder = value;
        }

        /**
         * Gets the value of the language property.
         *
         * @return
         *     possible object is
         *     {@link LanguageType }
         *
         */
        public LanguageType getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         *
         * @param value
         *     allowed object is
         *     {@link LanguageType }
         *
         */
        public void setLanguage(LanguageType value) {
            this.language = value;
        }

        /**
         * Gets the value of the mainLanguageDocumentChanged property.
         *
         */
        public boolean isMainLanguageDocumentChanged() {
            return mainLanguageDocumentChanged;
        }

        /**
         * Sets the value of the mainLanguageDocumentChanged property.
         *
         */
        public void setMainLanguageDocumentChanged(boolean value) {
            this.mainLanguageDocumentChanged = value;
        }

        /**
         * Gets the value of the attachedDocument property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attachedDocument property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttachedDocument().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument }
         *
         *
         */
        public List<MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument> getAttachedDocument() {
            if (attachedDocument == null) {
                attachedDocument = new ArrayList<MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument>();
            }
            return this.attachedDocument;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Language" type="{https://simisinfo.refdata.ch/MedicinalDocuments/1.0/}LanguageType"/>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Period">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Start" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DocumentReference" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "language",
            "description",
            "period",
            "documentReference"
        })
        public static class AttachedDocument {

            @XmlElement(name = "Language", required = true)
            @XmlSchemaType(name = "string")
            protected LanguageType language;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "Period", required = true)
            protected MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.Period period;
            @XmlElement(name = "DocumentReference", required = true)
            protected List<MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.DocumentReference> documentReference;

            /**
             * Gets the value of the language property.
             *
             * @return
             *     possible object is
             *     {@link LanguageType }
             *
             */
            public LanguageType getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             *
             * @param value
             *     allowed object is
             *     {@link LanguageType }
             *
             */
            public void setLanguage(LanguageType value) {
                this.language = value;
            }

            /**
             * Gets the value of the description property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the period property.
             *
             * @return
             *     possible object is
             *     {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.Period }
             *
             */
            public MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.Period getPeriod() {
                return period;
            }

            /**
             * Sets the value of the period property.
             *
             * @param value
             *     allowed object is
             *     {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.Period }
             *
             */
            public void setPeriod(MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.Period value) {
                this.period = value;
            }

            /**
             * Gets the value of the documentReference property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the documentReference property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDocumentReference().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.DocumentReference }
             *
             *
             */
            public List<MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.DocumentReference> getDocumentReference() {
                if (documentReference == null) {
                    documentReference = new ArrayList<MedicinalDocumentsBundles.MedicinalDocumentsBundle.AttachedDocument.DocumentReference>();
                }
                return this.documentReference;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "contentType",
                "url"
            })
            public static class DocumentReference {

                @XmlElement(name = "ContentType", required = true)
                protected String contentType;
                @XmlElement(name = "Url", required = true)
                @XmlSchemaType(name = "anyURI")
                protected String url;

                /**
                 * Gets the value of the contentType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getContentType() {
                    return contentType;
                }

                /**
                 * Sets the value of the contentType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setContentType(String value) {
                    this.contentType = value;
                }

                /**
                 * Gets the value of the url property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Start" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "start"
            })
            public static class Period {

                @XmlElement(name = "Start", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar start;

                /**
                 * Gets the value of the start property.
                 *
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public XMLGregorianCalendar getStart() {
                    return start;
                }

                /**
                 * Sets the value of the start property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public void setStart(XMLGregorianCalendar value) {
                    this.start = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "identifier",
            "name"
        })
        public static class Holder {

            @XmlElement(name = "Identifier", required = true)
            protected String identifier;
            @XmlElement(name = "Name", required = true)
            protected String name;

            /**
             * Gets the value of the identifier property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getIdentifier() {
                return identifier;
            }

            /**
             * Sets the value of the identifier property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setIdentifier(String value) {
                this.identifier = value;
            }

            /**
             * Gets the value of the name property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "identifier"
        })
        public static class RegulatedAuthorization {

            @XmlElement(name = "Identifier", required = true)
            protected List<String> identifier;

            /**
             * Gets the value of the identifier property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the identifier property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIdentifier().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             *
             *
             */
            public List<String> getIdentifier() {
                if (identifier == null) {
                    identifier = new ArrayList<String>();
                }
                return this.identifier;
            }

        }

    }

}
